import Link from "next/link";
import { AlertBell } from "@/components/alert-bell";
import { MobileNav, NavLinks } from "@/components/nav-links";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireSession, type UserRole } from "@/lib/auth/session";
import { signOutAction } from "../(auth)/actions";

const ROLE_LABEL: Record<UserRole, string> = {
  admin: "Admin",
  executive: "Executive",
  ops_manager: "Ops manager",
  analyst: "Analyst",
  data_entry: "Data entry",
  auditor: "Auditor",
};

export default async function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await requireSession();

  return (
    <div className="flex min-h-screen flex-col">
      <header className="border-b bg-card print:hidden">
        <div className="mx-auto flex h-14 max-w-7xl items-center justify-between gap-2 px-4 sm:px-6">
          <div className="flex items-center gap-2">
            <MobileNav />
            <Link href="/dashboard" className="flex items-center gap-2">
              <div className="h-6 w-6 rounded bg-primary" />
              <span className="text-sm font-semibold tracking-tight">
                PR Freight Intelligence
              </span>
            </Link>
          </div>
          <NavLinks />
          <div className="flex items-center gap-3">
            <AlertBell />
            <div className="hidden flex-col items-end text-xs leading-tight sm:flex">
              <span className="text-foreground">
                {session.fullName ?? session.email}
              </span>
              <Badge variant="secondary" className="text-[10px]">
                {ROLE_LABEL[session.role]}
              </Badge>
            </div>
            <form action={signOutAction}>
              <Button type="submit" variant="outline" size="sm">
                Sign out
              </Button>
            </form>
          </div>
        </div>
      </header>
      <div className="hidden print:block print:px-6 print:py-4">
        <div className="text-sm font-semibold">
          Pakistan Railways — Freight Intelligence Platform
        </div>
        <div className="text-xs text-muted-foreground">
          Generated by {session.fullName ?? session.email} ·{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </div>
      </div>
      <main className="mx-auto w-full max-w-7xl flex-1 px-4 py-8 sm:px-6">
        {children}
      </main>
    </div>
  );
}
